const data = {
  shipping: [
    {
      '0': [
        {
          PLANT_TYPE: 'Plant',
          DEST_PLANT_FULL_MIN: '2299 - Southern Regional DC-ExtOps/DC',
          ACTUAL_DELIVERED_QTY: 953.46224,
          SHIP_PLANT_LONG_MIN: -84.1492,
          SHIP_PLANT_GROUP_FULL_MAX: '2833 - Marinette Global Sales Mill',
          SHIP_PLANT_LONG: -84.1492,
          SHIP_PLANT_LAT: 33.445,
          SHIP_PLANT_GROUP_FULL_MIN: '2833 - Marinette Global Sales Mill',
          DEST_PLANT_FULL_MAX: '2299 - Southern Regional DC-ExtOps/DC',
          PLANT: '2299',
          'On Hand Qty (GSU)': 'On Hand Qty (GSU)',
          SHIP_PLANT_LAT_MIN: 33.445,
        },
        {
          PLANT_TYPE: 'Plant',
          DEST_PLANT_FULL_MIN: '2299 - Southern Regional DC-ExtOps/DC',
          ACTUAL_DELIVERED_QTY: 953.46224,
          SHIP_PLANT_LONG_MIN: -87.65006,
          SHIP_PLANT_GROUP_FULL_MAX: '2833 - Marinette Global Sales Mill',
          SHIP_PLANT_LONG: -87.65006,
          SHIP_PLANT_LAT: 45.10095,
          SHIP_PLANT_GROUP_FULL_MIN: '2833 - Marinette Global Sales Mill',
          DEST_PLANT_FULL_MAX: '2299 - Southern Regional DC-ExtOps/DC',
          PLANT: '2833',
          'On Hand Qty (GSU)': 'On Hand Qty (GSU)',
          SHIP_PLANT_LAT_MIN: 45.10095,
        },
      ],
    },
    {
      '1': [
        {
          PLANT_TYPE: 'Plant',
          DEST_PLANT_FULL_MIN: '2358 - Eastern Regional - ERDC',
          ACTUAL_DELIVERED_QTY: 800.46224,
          SHIP_PLANT_LONG_MIN: -87.65006,
          SHIP_PLANT_GROUP_FULL_MAX: '2320 - Beech Island Global Sales Mill',
          SHIP_PLANT_LONG: -119.487016,
          SHIP_PLANT_LAT: 47.086956,
          SHIP_PLANT_GROUP_FULL_MIN: '2320 - Beech Island Global Sales Mill',
          DEST_PLANT_FULL_MAX: '2358 - Eastern Regional - ERDC',
          PLANT: '2358',
          'On Hand Qty (GSU)': 'On Hand Qty (GSU)',
          SHIP_PLANT_LAT_MIN: 45.10095,
        },
        {
          PLANT_TYPE: 'Plant',
          DEST_PLANT_FULL_MIN: '2358 - Eastern Regional - ERDC',
          ACTUAL_DELIVERED_QTY: 300.46224,
          SHIP_PLANT_LONG_MIN: -84.1492,
          SHIP_PLANT_GROUP_FULL_MAX: '2320 - SOUTHWEST DC -ExtOps/DC',
          SHIP_PLANT_LONG: -101.282821,
          SHIP_PLANT_LAT: 32.604675,
          SHIP_PLANT_GROUP_FULL_MIN: '2320 - SOUTHWEST DC -ExtOps/DC',
          DEST_PLANT_FULL_MAX: '2358 - Eastern Regional - ERDC',
          PLANT: '2320',
          'On Hand Qty (GSU)': 'On Hand Qty (GSU)',
          SHIP_PLANT_LAT_MIN: 33.445,
        },
      ],
    },
    {
      '2': [
        {
          PLANT_TYPE: 'Plant',
          DEST_PLANT_FULL_MIN: '2336 - North Central Overflow Ext Ops',
          ACTUAL_DELIVERED_QTY: 800.46224,
          SHIP_PLANT_LONG_MIN: -87.65006,
          SHIP_PLANT_GROUP_FULL_MAX: '2320 - SOUTHWEST DC -ExtOps/DC',
          SHIP_PLANT_LONG: -109.487016,
          SHIP_PLANT_LAT: 47.086956,
          SHIP_PLANT_GROUP_FULL_MIN: '2320 - SOUTHWEST DC -ExtOps/DC',
          DEST_PLANT_FULL_MAX: '2336 - North Central Overflow Ext Ops',
          PLANT: '2336',
          'On Hand Qty (GSU)': 'On Hand Qty (GSU)',
          SHIP_PLANT_LAT_MIN: 45.10095,
        },
        {
          PLANT_TYPE: 'Plant',
          DEST_PLANT_FULL_MIN: '2028 - Beech Island Global Sales Mill',
          ACTUAL_DELIVERED_QTY: 300.46224,
          SHIP_PLANT_LONG_MIN: -84.1492,
          SHIP_PLANT_GROUP_FULL_MAX: '2320 - SOUTHWEST DC -ExtOps/DC',
          SHIP_PLANT_LONG: -101.282821,
          SHIP_PLANT_LAT: 32.604675,
          SHIP_PLANT_GROUP_FULL_MIN: '2320 - SOUTHWEST DC -ExtOps/DC',
          DEST_PLANT_FULL_MAX: '2028 - Beech Island Global Sales Mill',
          PLANT: '2320',
          'On Hand Qty (GSU)': 'On Hand Qty (GSU)',
          SHIP_PLANT_LAT_MIN: 33.445,
        },
      ],
    },
  ],
};

export default data;
